package fr.pinguet62.jpavalidator.comp.id.generatedvalue;

import static java.util.Arrays.asList;

import java.lang.reflect.Field;
import java.util.List;

import javax.persistence.GeneratedValue;

import fr.pinguet62.jpavalidator.comp.Validator;

public class BaseGeneratedvalueValidator extends Validator {

    private GeneratedValue generatedValue;

    public BaseGeneratedvalueValidator(String tableName) {
        super(tableName);
    }

    @Override
    protected List<Validator> getAvailableNextValidators() {
        return asList(new AutoGeneratedIdValidator(tableName, generatedValue),
                new IdentityGeneratedIdValidator(tableName, generatedValue),
                new SequenceGeneratedIdValidator(tableName, generatedValue));
    }

    @Override
    protected void process(Field field) {
        generatedValue = field.getDeclaredAnnotation(GeneratedValue.class);

        processNext(field);
    }

    @Override
    protected boolean support(Field field) {
        return field.isAnnotationPresent(GeneratedValue.class);
    }

}