package fr.pinguet62.jpavalidator.comp.id.generatedvalue;

import static java.util.Arrays.asList;

import java.lang.reflect.Field;

import javax.persistence.GeneratedValue;

import fr.pinguet62.jpavalidator.comp.Validator;
import fr.pinguet62.jpavalidator.processor.AbstractProcessor;
import fr.pinguet62.jpavalidator.processor.OnlyOneProcessor;

public class BaseGeneratedvalueValidator extends Validator {

    private GeneratedValue generatedValue;

    public BaseGeneratedvalueValidator(String tableName) {
        super(tableName);
    }

    @Override
    protected void doProcess(Field field) {
        generatedValue = field.getDeclaredAnnotation(GeneratedValue.class);
    }

    @Override
    protected AbstractProcessor getProcessor() {
        return new OnlyOneProcessor(asList(new AutoGeneratedIdValidator(tableName, generatedValue),
                new IdentityGeneratedIdValidator(tableName, generatedValue),
                new SequenceGeneratedIdValidator(tableName, generatedValue)));
    }

    @Override
    public boolean support(Field field) {
        return field.isAnnotationPresent(GeneratedValue.class);
    }

}