package fr.pinguet62.jpavalidator.comp.id.generatedvalue;

import static javax.persistence.GenerationType.IDENTITY;

import java.lang.reflect.Field;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;

import fr.pinguet62.jpavalidator.checker.JdbcMetadataChecker;
import fr.pinguet62.jpavalidator.comp.ColumnException;

public class IdentityGeneratedIdValidator extends AbstractGeneratedvalueValidator {

    public IdentityGeneratedIdValidator(String tableName, GeneratedValue generatedValue) {
        super(tableName, generatedValue);
    }

    @Override
    protected void process(Field field) {
        Column column = field.getDeclaredAnnotation(Column.class);
        String columnName = column.name();

        // Auto-increment
        if (!JdbcMetadataChecker.INSTANCE.checkAutoIncrement(tableName, columnName, true))
            throw new ColumnException(tableName, columnName, "is not 'auto-increment'");

        // Generated by: identity
        if (!JdbcMetadataChecker.INSTANCE.checkAutoIncrementByIdentity(tableName, columnName))
            throw new ColumnException(tableName, columnName, "is not 'generated as identity'");
        if (JdbcMetadataChecker.INSTANCE.checkIsAutoIncrementByAnySequence(tableName, columnName))
            throw new ColumnException(tableName, columnName, "is 'generated as sequence'");

        processNext(field);
    }

    @Override
    protected boolean support(Field field) {
        return field.getDeclaredAnnotation(GeneratedValue.class).strategy().equals(IDENTITY);
    }

}