package fr.pinguet62.jpavalidator.comp.id;

import java.lang.reflect.Field;

import javax.persistence.Column;
import javax.persistence.Id;

import fr.pinguet62.jpavalidator.checker.JdbcMetadataChecker;
import fr.pinguet62.jpavalidator.comp.ColumnException;
import fr.pinguet62.jpavalidator.comp.Validator;

public class IdentityGeneratedIdValidator extends Validator {

    public IdentityGeneratedIdValidator(String tableName) {
        super(tableName);
    }

    @Override
    protected void process(Field field) {
        Column column = field.getDeclaredAnnotation(Column.class);
        String columnName = column.name();

        // Auto-increment
        if (!JdbcMetadataChecker.INSTANCE.checkAutoIncrement(tableName, columnName, true))
            throw new ColumnException(tableName, columnName, "is not 'auto-increment'");

        // Generated by: identity
        if (!JdbcMetadataChecker.INSTANCE.checkAutoIncrementByIdentity(tableName, columnName))
            throw new ColumnException(tableName, columnName, "is not 'generated as identity'");
        if (JdbcMetadataChecker.INSTANCE.checkIsAutoIncrementByAnySequence(tableName, columnName))
            throw new ColumnException(tableName, columnName, "is 'generated as sequence'");

        processNext(field);
    }

    @Override
    protected boolean support(Field field) {
        return field.isAnnotationPresent(Id.class);
    }

}