create sequence ID_GENERATED_SEQUENCE_OK_SEQUENCE;

create table ID_GENERATED_SEQUENCE_INVALID (
	invalid int /* not null*/ primary key
);

create table ID_GENERATED_SEQUENCE_OK (
	ok int /* not null*/ generated by default as sequence ID_GENERATED_SEQUENCE_OK_SEQUENCE primary key
);